POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "phoneNumber": "+84784030266",
  "password": "12345678"
}

###
POST http://localhost:3001/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RJZCI6IjMwNzc2NzJlLTA5MDItNDM2MS1iY2U3LWIxODAxMjcxNWZkYyIsInBob25lTnVtYmVyIjoiKzg0Nzg0MDMwMjY2IiwiaWF0IjoxNjg1NjMyMzg2LCJleHAiOjE2ODU2MzI2ODZ9.l86ZxnW9OCzMsxuJjHMGQH4hIDM5zb0ToZ-7daWEUpA